it_food_center/food_center/urls.py
from django.urls import path
from food_center.views import *  

urlpatterns = [
    path('', LoadingView.as_view(), name='loading'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('home/', HomeView.as_view(), name='home'),
    path('home/shop/<int:restaurant_id>', ShopView.as_view(), name='shop'),
    path('home/shop/order/<int:fooditem_id>', OrderView.as_view(), name='order'),
    path('home/shop/qrcode/<int:order_id>', QRcodeView.as_view(), name='qrcode'),
    path('status/', StatusView.as_view(), name='status'),
    path('home/logout', LogoutView.as_view(), name="logout"),

    path('c_orderStatus/', c_orderStatusView.as_view(), name='c_orderStatus'),
    path('c_orderStatus/cancel/<int:order_id>',c_orderStatusCancelView.as_view(), name='c_orderCancel'),
    path('c_orderStatus/delete/<int:order_id>',c_orderStatusDeleteView.as_view(), name='c_orderDelete'),
    path('c_orderStatus/edit/<int:order_id>', c_orderStatusEditView.as_view(), name='c_orderEdit'),
    path('order/add/', OrderAddView.as_view(), name='order_add'),
    path('c_fooditem/', c_FoodItemView.as_view(), name='c_fooditem'),
    path('c_fooditem/delete/<int:fooditem_id>',c_fooditemDeleteView.as_view(), name='c_fooditemDelete'),
    path('c_fooditem/edit/<int:fooditem_id>', c_fooditemEditView.as_view(), name='c_orderEdit'),
    path('c_restaurant/', c_FoodItemView.as_view(), name='c_restaurant'),
]

it_food_center/it_food_center/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('itfoodcenter/', include('food_center.urls')),
]

it_food_center/food_center/models.py
from django.db import models
from django.contrib.auth.models import User

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    gmail = models.EmailField(max_length=200)  # เปลี่ยนเป็น EmailField สำหรับความถูกต้อง

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Cook(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=200, null=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class ResturantCategory(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Restaurant(models.Model):  
     
    class StatusChoice(models.TextChoices):
        OPEN = "O", "เปิด"
        CLOSED = "C", "ปิด"

    name = models.CharField(max_length=150)
    description = models.CharField(max_length=150)
    cook = models.ForeignKey(Cook, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=StatusChoice.choices, default=StatusChoice.OPEN)
    category = models.ManyToManyField(ResturantCategory) 

    def __str__(self):
        return self.name

class FoodItem(models.Model):
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField()
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)  # แก้ชื่อเป็น restaurant

    def __str__(self):
        return self.name

class Order(models.Model):

    class StatusChoice(models.TextChoices):
        WAITING = "W", "รอการยืนยัน"
        IN_KITCHEN = "C", "อยู่ในครัว"
        ALREADY_COOKED = "AC", "ทำเสร็จแล้ว"
        FINISHED = "F", "เสร็จสิ้น"
        REJECT = "R", "ยกเลิก"
    


    FoodItem = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
    description = models.CharField(max_length=250)
    order_status = models.CharField(max_length=10, choices=StatusChoice.choices, default=StatusChoice.WAITING)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    order_datetime = models.DateTimeField(auto_now_add=True)
    price=models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Order {self.id} by {self.student}"

it_food_center/food_center/forms.py
import datetime
from typing import Any
from .models import *
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
import re

class OrderForm(forms.Form):
    size = forms.ChoiceField(choices=[
        ('ธรรมดา', 'ธรรมดา เพิ่ม ฿ 0'),
        ('พิเศษ', 'พิเศษ เพิ่ม ฿ 10'),
    ], widget=forms.RadioSelect)
    
    quantity = forms.IntegerField(min_value=1, initial=1)
    description = forms.CharField(widget=forms.Textarea, required=False)

class OrderAddForm(forms.Form):
    food_item = forms.ModelChoiceField(queryset=FoodItem.objects.all(), label="เลือกเมนู")
    size = forms.ChoiceField(choices=[
        ('ธรรมดา', 'ธรรมดา เพิ่ม ฿ 0'),
        ('พิเศษ', 'พิเศษ เพิ่ม ฿ 10'),
    ], widget=forms.RadioSelect)
    quantity = forms.IntegerField(min_value=1, initial=1, label="จำนวน")
    description = forms.CharField(widget=forms.Textarea, required=False, label="คำอธิบาย")
    student = forms.ModelChoiceField(queryset=Student.objects.all(), label="นักเรียน")

class OrderEditForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['FoodItem', 'description', 'order_status','price']

class FoodItemEditForm(forms.ModelForm):
    class Meta:
        model = FoodItem
        fields = ['name', 'description','quantity','price'] 

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=150, required=True)
    last_name = forms.CharField(max_length=150, required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2',)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError("ชื่อผู้ใช้นี้ถูกใช้งานแล้ว")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("อีเมลนี้ถูกใช้งานแล้ว")
        if not email.endswith('@kmitl.ac.th'):
            raise ValidationError("อีเมลต้องลงท้ายด้วย @kmitl.ac.th")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("รหัสผ่านไม่ตรงกัน")

        if not self.is_password_strong(password1):
            raise ValidationError("รหัสผ่านควรมีตัวอักษรใหญ่ ตัวอักษรเล็ก ตัวเลข และสัญลักษณ์พิเศษอย่างน้อย 5 ตัว")

        return password2

    def is_password_strong(self, password):
        return (
            len(password) >= 5 and
            re.search(r'[A-Z]', password) and
            re.search(r'[a-z]', password) and
            re.search(r'[0-9]', password)
        )
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

it_food_center/food_center/views.py
from django.views import View
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render, redirect
from food_center.models import *
from .forms import *
from django.contrib.auth import logout, login
from .models import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Group

class LoadingView(View):
    def get(self, request):
        return render(request, 'loading.html')

class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('login')

class RegisterView(View):
    def get(self, request):
        form = RegistrationForm()
        return render(request, 'register.html', {'form': form})

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()  
            Student.objects.create(
                user=user,
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                gmail=user.email 
            )
            student_group = Group.objects.get(name='student')
            user.groups.add(student_group)
            return redirect('login')
        return render(request, 'register.html', {'form': form})

class LoginView(View):

    def get(self, request):
        return render(request, 'login.html', {"form": AuthenticationForm()})
    
    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user() 
            login(request, user)

            if user.username == "it65070191":
                return redirect('../../admin/')
            elif hasattr(user, 'cook'):
                return redirect('c_orderStatus')
            else:
                return redirect('home')
        
        return render(request, 'login.html', {"form": form})

class HomeView(LoginRequiredMixin,PermissionRequiredMixin, View):
    login_url = '/login/'
    permission_required = ["food_center.change_student"]

    def get(self, request):
        thai = Restaurant.objects.filter(category__name="ร้านอาหารไทย")
        japan = Restaurant.objects.filter(category__name="ร้านอาหารญี่ปุ่น")
        student = Student.objects.get(user__username=request.user.username)

        context = {
            "thai": thai,
            "japan": japan,
            "student": student,
        }
        return render(request, 'home.html', context)

class OrderView(LoginRequiredMixin,PermissionRequiredMixin, View):
    login_url = '/login/'
    permission_required = ["food_center.change_student"]

    def get(self, request, fooditem_id):
        food_item = FoodItem.objects.get(id=fooditem_id)
        form = OrderForm()
        context = {
            "food_item": food_item,
            "form": form
        }
        return render(request, 'order.html', context)

    def post(self, request, fooditem_id):
        form = OrderForm(request.POST)
        if form.is_valid():
            food_item = FoodItem.objects.get(id=fooditem_id)
            quantity = form.cleaned_data['quantity']
            size = form.cleaned_data['size']
            description = form.cleaned_data['description']
            student = Student.objects.get(user__username=request.user.username)

            if size == "พิเศษ":
                price = (food_item.price + 10) * quantity
            else:
                price = food_item.price * quantity
            
            order = Order.objects.create(
                FoodItem=food_item,
                description=f"จำนวน : {quantity} ขนาด : {size} เพิ่มเติม: {description}",
                student=student,
                price=price
            )
            return redirect('qrcode', order_id=order.id)
        else:
            food_item = FoodItem.objects.get(id=fooditem_id)
            context = {
                "food_item": food_item,
                "form": form
            }
            return render(request, 'order.html', context)

class QRcodeView(LoginRequiredMixin,PermissionRequiredMixin, View):
    login_url = '/login/'
    permission_required = ["food_center.change_student"]

    def get(self, request, order_id):
        order = Order.objects.get(id=order_id)
        context = {
            "order_id": order_id,
            "order": order
        }
        return render(request, 'qrcode.html', context)

class ShopView(LoginRequiredMixin,PermissionRequiredMixin, View):
    login_url = '/login/'
    permission_required = ["food_center.change_student"]

    def get(self, request, restaurant_id):
        restaurant = Restaurant.objects.get(id=restaurant_id)
        fooditems = FoodItem.objects.filter(restaurant=restaurant)
        student = Student.objects.get(user__username=request.user.username)
        context = {
            "restaurant_id": restaurant_id,
            "restaurants": restaurant,
            "foodItems": fooditems,
            "student":student
        }
        return render(request, 'shop.html', context)

class StatusView(LoginRequiredMixin,PermissionRequiredMixin, View):
    login_url = '/login/'
    login_url = '/login/'
    permission_required = ["food_center.change_student"]

    def get(self, request):
        student = Student.objects.get(user__username=request.user.username)
        orders = Order.objects.filter(student=student)
        return render(request, 'status.html', {"orders": orders})
    
# แม่ค้า---------------------------------------------------------------------------------------------------------------------

class c_orderStatusView(LoginRequiredMixin,PermissionRequiredMixin, View):
    login_url = '/login/'
    permission_required = ["food_center.change_cook"]

    def get(self, request):
        cook = Cook.objects.get(user__username=request.user.username)
        restaurant = Restaurant.objects.get(cook=cook.id)
        order = Order.objects.filter(FoodItem__restaurant=restaurant)

        context = {
            "cook": cook,
            "restaurant":restaurant,
            "orders":order
        }
        return render(request, 'c_orderStatus.html', context)

class c_orderStatusDeleteView(LoginRequiredMixin, View):
    login_url = '/login/'
    permission_required = ["food_center.change_cook"]
    def get(self, request,order_id):
        order = Order.objects.get(id = order_id)
        order.delete()
        return redirect('c_orderStatus')
    
class c_orderStatusCancelView(LoginRequiredMixin, View):
    login_url = '/login/'
    permission_required = ["food_center.change_cook"]
    def get(self, request,order_id):
        order = Order.objects.get(id = order_id)
        print(order)
        order.order_status="R"
        order.save()
        return redirect('c_orderStatus')

class c_orderStatusEditView(LoginRequiredMixin,PermissionRequiredMixin, View):
    login_url = '/login/'
    permission_required = ["food_center.change_cook"]
    def get(self, request, order_id):
        order = Order.objects.get(id=order_id)  # ใช้พารามิเตอร์ที่ถูกต้อง
        food_item = order.FoodItem
        form = OrderEditForm(instance=order)
        # ถ้าต้องการส่งฟอร์มไปยัง template
        return render(request, 'c_orderEdit.html', {'form': form, 'order': order ,'food_item':food_item})

    def post(self, request, order_id):
        order = Order.objects.get(id=order_id)
        food_item = order.FoodItem
        form = OrderEditForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect('c_orderStatus') 
        return render(request, 'c_orderEdit.html', {'form': form, 'order': order ,'food_item':food_item})
    
class OrderAddView(LoginRequiredMixin, PermissionRequiredMixin, View):
    login_url = '/login/'
    permission_required = ['food_center.add_order']

    def get(self, request):
        cook = Cook.objects.get(user=request.user)
        restaurant = Restaurant.objects.get(cook=cook)
        form = OrderAddForm()
        form.fields['food_item'].queryset = FoodItem.objects.filter(restaurant=restaurant)
        context = {
            'form': form,
            'restaurant': restaurant
        }
        return render(request, 'c_orderAdd.html', context)

    def post(self, request):
        cook = Cook.objects.get(user=request.user)
        restaurant = Restaurant.objects.get(cook=cook)
        form = OrderAddForm(request.POST)
        form.fields['food_item'].queryset = FoodItem.objects.filter(restaurant=restaurant)
        
        if form.is_valid():
            food_item = form.cleaned_data['food_item']
            quantity = form.cleaned_data['quantity']
            size = form.cleaned_data['size']
            description = form.cleaned_data['description']
            student = form.cleaned_data['student']

            if size == "พิเศษ":
                price = (food_item.price + 10) * quantity
            else:
                price = food_item.price * quantity

            order = Order.objects.create(
                FoodItem=food_item,
                description=f"จำนวน : {quantity} ขนาด : {size} เพิ่มเติม: {description}",
                student=student,
                price=price
            )
            return redirect('c_orderStatus')
        print(form.errors) 
        context = {
            'form': form,
            'restaurant': restaurant
        }
        return render(request, 'c_orderAdd.html', context)

class c_FoodItemView(LoginRequiredMixin, PermissionRequiredMixin,View):
    login_url = '/login/'
    permission_required = ["food_center.change_cook"]
    login_url = '/login/'

    def get(self, request):

it_food_center/food_center/templates/c_orderStatus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/c_orderStatus.css' %}" />
    <title>Home</title>
</head>
<body>
    {% include 'c_nav.html' %}
    <main>
        <div class="category">
            <h1>{{restaurant.name}} : จัดการออเดอร์</h1>
            <div class="category-shop">
                {% for order in orders %}
                {% if order.order_status == "F" or order.order_status == "R" %}
                <div style="opacity: 0.4; box-shadow : 0px 0px 0px rgba(0, 0, 0, 0.3);;" class="category-shop-list">
                    <h3 class="category-shop-list-name">{{ order.FoodItem.name }}</h3>
                    <h4 class="category-shop-list-name">นักศึกษา : {{ order.student.first_name }} {{ order.student.last_name }}</h4>
                    {% if order.FoodItem.name == "แกงเขียวหวาน" %}
                    <img src="{% static '/restaurant/thai/keaw.png' %}" alt="shop-list-img">
                    {% endif %}
                    {% if order.FoodItem.name == "ข้าวผัดกระเพรา" %}
                    <img src="{% static '/restaurant/thai/krapow.png' %}" alt="shop-list-img">
                    {% endif %}
                    {% if order.FoodItem.name == "ต้มยำกุ้ง" %}
                    <img src="{% static '/restaurant/thai/tomyum.png' %}" alt="shop-list-img">
                    {% endif %}
                    {% if order.FoodItem.name == "ซูชิแซลมอน" %}
                    <img src="{% static '/restaurant/japan/salmon.png' %}" alt="shop-list-img">
                    {% endif %}
                    {% if order.FoodItem.name == "ซูชิปลาหมึก" %}
                    <img style="width: 180px;" src="{% static '/restaurant/japan/octo.png' %}" alt="shop-list-img">
                    {% endif %}
                    {% if order.FoodItem.name == "ซูชิรวม" %}
                    <img src="{% static '/restaurant/japan/mix.png' %}" alt="shop-list-img">
                    {% endif %}
                    <div class="category-shop-list-name">{{ order.description }}</div>
                    {% if order.order_status == "W" %}
                    <div style="color: #ccc;">สถานะ : {{ order.get_order_status_display }}</div>
                    {% endif %}
                    {% if order.order_status == "F" %}
                    <div style="color: #000000;">สถานะ : {{ order.get_order_status_display }}</div>
                    {% endif %}
                    {% if order.order_status == "C" %}
                    <div class="status">
                    <div style="color: #f0ec20;">สถานะ : {{ order.get_order_status_display }}</div>
                    </div>
                    {% endif %}
                    {% if order.order_status == "AC" %}
                    <div style="color: #00ff37;">สถานะ : {{ order.get_order_status_display }}</div>
                    {% endif %}
                    <div style="color: #ff0000;">ราคา : {{ order.price|floatformat:2 }}</div>
                    <div class="button-status">
                        <button class="button-reject" disabled>ยกเลิก</button>
                        <button disabled class="button-edit"disabled>แก้ใข</button>
                        <button class="button-delete" onclick="confirmDelete({{ order.id }})">ลบ</button>
                    </div>
                </div>
                {% else %}
                <div class="category-shop-list">
                    <h3 class="category-shop-list-name">{{ order.FoodItem.name }}</h3>
                    <h4 class="category-shop-list-name">นักศึกษา : {{ order.student.first_name }} {{ order.student.last_name }}</h4>
                    {% if order.FoodItem.name == "แกงเขียวหวาน" %}
                    <img src="{% static '/restaurant/thai/keaw.png' %}" alt="shop-list-img">
                    {% endif %}
                    {% if order.FoodItem.name == "ข้าวผัดกระเพรา" %}
                    <img src="{% static '/restaurant/thai/krapow.png' %}" alt="shop-list-img">
                    {% endif %}
                    {% if order.FoodItem.name == "ต้มยำกุ้ง" %}
                    <img src="{% static '/restaurant/thai/tomyum.png' %}" alt="shop-list-img">
                    {% endif %}
                    {% if order.FoodItem.name == "ซูชิแซลมอน" %}
                    <img src="{% static '/restaurant/japan/salmon.png' %}" alt="shop-list-img">
                    {% endif %}
                    {% if order.FoodItem.name == "ซูชิปลาหมึก" %}
                    <img style="width: 180px;" src="{% static '/restaurant/japan/octo.png' %}" alt="shop-list-img">
                    {% endif %}
                    {% if order.FoodItem.name == "ซูชิรวม" %}
                    <img src="{% static '/restaurant/japan/mix.png' %}" alt="shop-list-img">
                    {% endif %}
                    <div class="category-shop-list-name">{{ order.description }}</div>
                    {% if order.order_status == "W" %}
                    <div style="color: #ccc;">สถานะ : {{ order.get_order_status_display }}</div>
                    {% endif %}
                    {% if order.order_status == "C" %}
                    <div class="status">
                    <div style="color: #f0ec20;">สถานะ : {{ order.get_order_status_display }}</div>
                    </div>
                    {% endif %}
                    {% if order.order_status == "AC" %}
                    <div style="color: #00ff37;">สถานะ : {{ order.get_order_status_display }}</div>
                    {% endif %}
                    <div style="color: #ff0000;">ราคา : {{ order.price|floatformat:2 }}</div>
                    <div class="button-status">
                        <button class="button-reject" onclick="confirmCancel({{ order.id }})">ยกเลิก</button>
                        <button class="button-edit" onclick="window.location.href='edit/{{ order.id }}'">แก้ไข</button>
                        <button class="button-delete" onclick="confirmDelete({{ order.id }})">ลบ</button>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <button class="add_order" onclick="window.location.href='{% url 'order_add' %}'">เพิ่มออเดอร์</button>
    </main>
    <script>
        function confirmCancel(orderID) {
            if (confirm('ยกเลิกออเดอร์')) {
                window.location.href = '../c_orderStatus/cancel/' + orderID;
            }
        }
        function confirmDelete(orderID) {
            if (confirm('ลบออเดอร์')) {
                window.location.href = '../c_orderStatus/delete/' + orderID;
            }
        }
    </script>
</body>
</html>

it_food_center/food_center/templates/loading.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loading</title>
    <link rel="stylesheet" href="{% static '/css/loading.css' %}" />
    <script>
        function redirectToLogin() {
            window.location.href = "{% url 'login' %}"; 
        }
        
        setTimeout(redirectToLogin, 5000);
    </script>
</head>
<body>
    <img src="{% static '/logo-icon/icon_png.png' %}" alt="My image">
</body>
</html>

it_food_center/food_center/templates/status.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>รายการสั่งซื้อ</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px;
            background-image: url('../../static/background/loading.jpg');
            background-size: cover;
            background-position: center;
            height: 100vh;
            margin: 0;
        }

        .order-container {
            background-color: #ffffff;
            width: 600px;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
        }

        .back-button {
            display: inline-block;
            font-size: 16px;
            margin-bottom: 10px;
            cursor: pointer;
            text-decoration: none;
            color: #333;
        }

        .order-title {
            font-size: 24px;
            text-align: center;
            margin-bottom: 20px;
        }

        .image-container {
            text-align: center;
            margin-bottom: 20px;
        }

        .image-container img {
            width: 100%;
            max-width: 400px;
            border-radius: 10px;
        }

        .menu-options {
            margin-bottom: 20px;
        }

        .menu-options label {
            display: block;
            margin-bottom: 5px;
            font-size: 18px;
        }

        .menu-options input {
            margin-right: 10px;
        }

        .extra-options {
            margin-bottom: 20px;
        }

        .extra-options input {
            margin-right: 10px;
        }

        .note-container {
            margin-bottom: 20px;
        }

        .note-container textarea {
            width: 100%;
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #ccc;
            resize: none;
            font-size: 16px;
        }

        .total-price {
            font-size: 20px;
            text-align: right;
            margin-bottom: 20px;
        }

        .order-button {
            background-color: #283988;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 25px;
            cursor: pointer;
            font-size: 18px;
            display: block;
            width: 100%;
            text-align: center;
        }

        .order-button:hover {
            background-color: #b6778c;
        }

        .order-form {
            width: 100%;
        }

        .category-shop-list {
            display: flex;
            /* ใช้ flexbox */
            align-items: center;
            /* จัดแนวแนวตั้ง */
            width: 93%;
            height: 50px;
            background-color: white;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.3);
            padding: 20px;
            text-align: center;
            margin-right: 20px;
            /* เพิ่มระยะห่างระหว่างรายการ */
            margin-bottom: 10px;
        }

        .category-shop-list img {
            width: 50px;
            height: 50px;
        }

        .category-shop-list-name {
            margin-left: 20px;
        }

        .category-shop-list-status {
            margin-left: auto;
        }
    </style>
</head>

<body>
    <form method="post" class="order-container">
        <a href="{% url 'home'%}" class="back-button">กลับ</a>
        <div class="category">
            <h1>Status :</h1>
            <div class="category-shop">
                {% if orders %}
                {% for order in orders %}
                {% if order.order_status == "F" %}
                {% else %}
                {% with foodItem=order.FoodItem %}
                <div class="category-shop-list">
                    {% if foodItem.name == "แกงเขียวหวาน" %}
                    <img src="{% static '/restaurant/thai/keaw.png' %}" alt="shop-list-img">
                    {% endif %}
                    {% if foodItem.name == "ข้าวผัดกระเพรา" %}
                    <img src="{% static '/restaurant/thai/krapow.png' %}" alt="shop-list-img">
                    {% endif %}
                    {% if foodItem.name == "ต้มยำกุ้ง" %}
                    <img src="{% static '/restaurant/thai/tomyum.png' %}" alt="shop-list-img">
                    {% endif %}
                    {% if foodItem.name == "ซูชิแซลมอน" %}
                    <img src="{% static '/restaurant/japan/salmon.png' %}" alt="shop-list-img">
                    {% endif %}
                    {% if foodItem.name == "ซูชิปลาหมึก" %}
                    <img style="width: 80px;" src="{% static '/restaurant/japan/octo.png' %}" alt="shop-list-img">
                    {% endif %}
                    {% if foodItem.name == "ซูชิรวม" %}
                    <img src="{% static '/restaurant/japan/mix.png' %}" alt="shop-list-img">
                    {% endif %}
                    <div class="category-shop-list-name">{{ order.FoodItem.name }}</div>
                    {% if order.order_status == "W" %}
                    <div style="color: #ccc;" class="category-shop-list-status">สถานะ : {{ order.get_order_status_display }}</div>
                    {% endif %}
                    {% if order.order_status == "C" %}
                    <div style="color: #f0ec20;" class="category-shop-list-status">สถานะ : {{ order.get_order_status_display }}</div>
                    {% endif %}
                    {% if order.order_status == "AC" %}
                    <div style="color: #00ff37;" class="category-shop-list-status">สถานะ : {{ order.get_order_status_display }}</div>
                    {% endif %}
                </div>
                {% endwith %}
                {% endif %}
                {% endfor %}
                {% else %}
                <div class="no-orders-message">ยังไม่มีออเดอร์</div>
                {% endif %}
            </div>
        </div>
    </form>
</body>

</html>